object Versions {
    const val pagerIndicatorsAccompanist: String = "0.24.11-rc"
    const val adjustAndroid: String = "4.30.1"
    const val material: String = "1.9.0"
    const val viewModelKtx: String = "2.5.0"
    const val coreKtx: String = "1.12.0"
    const val liveDataKtx: String = "2.5.0"
    const val espressoCore: String = "3.5.1"
    const val mockitoAndroid: String = "4.6.1"
    const val gradle = "8.1.0"
    const val kotlin = "1.9.0"
    const val coroutinesTest = "1.6.0"
    const val coroutines = "1.6.0"
    const val appCompat = "1.6.1"
    const val koin = "3.4.3"
    const val timber = "5.0.1"
    const val dagger = "2.42"
    const val daggerCompiler = "2.42"

    const val leakCanary = "2.8.1"
    const val apollo = "2.5.10"
    const val okHttp = "4.10.0"
    const val retrofit = "2.9.0"
    const val retrofitConverter = "2.1.0"
    const val junitExt = "1.1.5"
    const val junit = "4.13.2"

    const val compose = "1.2.1"
    const val composeBOM = "2023.09.02"
    const val composeCompiler = "1.5.2"
    const val composeAnimation = "1.2.1"
    const val composeUI = composeAnimation
    const val composeMaterial3 = "1.0.0-alpha01"
    const val activityCompose = "1.4.0"
    const val viewModelCompose = "2.5.0"
    const val composeFoundation = "1.2.0-rc03"
    const val navigationCompose = "2.6.0"
    const val composeMaterial: String = composeAnimation
    const val customView = "1.1.0"
    const val customViewPoolingContainer = "1.0.0-rc01"
    const val markdown: String = "0.3.0"

    const val accompanist = "0.22.0-rc"
    const val accompanistSystemUiController = "0.24.4-alpha"
    const val navigationMaterial = "0.24.1-alpha"
    const val constraintLayoutCompose = "1.0.0-rc02"

    const val googleAds = "20.5.0"
    const val coreTesting = "2.1.0"
    const val googleServices = "4.3.10"
    const val firebaseCrashlyticsGradle = "2.8.1"
    const val room = "2.6.0-rc01"
    const val googleFitness = "21.0.1"
    const val googleAuth = "20.4.1"
    const val firebaseBom = "31.0.2"
    const val firebaseAuthUI = "7.2.0"
    const val testRules = "1.4.0"
    const val coil = "1.4.0"

    const val moshi = "1.13.0"
    const val moshiAdapters = "1.9.2"
    const val accompanistWebView = "0.24.4-alpha"
    const val facebookLogin = "12.3.0"
    const val pagerAccompanist = "0.24.13-rc"
    const val oneSignalPlugin = "0.14.0"
    const val oneSignalLibrary = "4.8.0"
    const val swipeToRefresh = "0.30.0"
    const val gson = "2.9.0"
    const val permissions = "0.20.0"

    // Jetpack security
    const val crypto = "1.0.0"
    const val identityCredential = "1.0.0-alpha03"
    const val appAuthenticator = "1.0.0-alpha02"
}
